Klausuren/ontrack/config/routes.rb
Rails.application.routes.draw do
 
  root 'projects#index'
  resources :projects do
     resources :validations
  end

end

Klausuren/ontrack/app/models/project.rb
class Project < ActiveRecord::Base
	has_many :validations

	validates :title, length: { minimum: 5 }
	validates :description, presence: true
end

Klausuren/ontrack/app/models/validation.rb
class Validation < ActiveRecord::Base
  belongs_to :project

  validates :username, presence: true
  validates :comment, length: { minimum: 15 }
  RANKING_ITEM = [1,2,3,4,5]
  validates :ranking, inclusion: {in: RANKING_ITEM}
end

Klausuren/ontrack/app/controllers/validations_controller.rb
class ValidationsController < ApplicationController
  before_action :set_validation, only: [:show, :edit, :update, :destroy]
  before_action :set_project

  # GET /validations
  # GET /validations.json
  def index
    @validations = @project.validations
  end

  # GET /validations/1
  # GET /validations/1.json
  def show
  end

  # GET /validations/new
  def new
    @validation = @project.validations.new
  end

  # GET /validations/1/edit
  def edit
  end

  # POST /validations
  # POST /validations.json
  def create
    @validation = @project.validations.new(validation_params)

    respond_to do |format|
      if @validation.save
        format.html { redirect_to project_validation_path(@project.id, @validation.id), notice: 'Validation was successfully created.' }
        format.json { render :show, status: :created, location: @validation }
      else
        format.html { render :new }
        format.json { render json: @validation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /validations/1
  # PATCH/PUT /validations/1.json
  def update
    respond_to do |format|
      if @validation.update(validation_params)
        format.html { redirect_to project_validation_path, notice: 'Validation was successfully updated.' }
        format.json { render :show, status: :ok, location: @validation }
      else
        format.html { render :edit }
        format.json { render json: @validation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /validations/1
  # DELETE /validations/1.json
  def destroy
    @validation.destroy
    respond_to do |format|
      format.html { redirect_to project_validations_url, notice: 'Validation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_validation
      @validation = Validation.find(params[:id])
    end

    def set_project
      @project = Project.find(params[:project_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def validation_params
      params.require(:validation).permit(:project_id, :comment, :username, :ranking, :project_id)
    end
end

Klausuren/ontrack/app/helpers/validations_helper.rb
module ValidationsHelper

	def number_to(i)
		if i == 1
			"sehr schlecht" 
		elsif i == 2
			"schlecht"
		elsif i == 3
			"okay"
		elsif i == 4
			"gut"
		elsif i == 5
			"sehr gut"
		else
			 "Keine Daten"
		end
	end

		def to_star(i)
		if i == 1
			"*" 
		elsif i == 2
			"**"
		elsif i == 3
			"***"
		elsif i == 4
			"****"
		elsif i == 5
			"*****"
		else
			 "Keine Daten"
		end
	end

	def durchschnitt(validations)
		@Anzahl = 0.0
		@Count = 0.0

		validations.each do |validation|
     	@Anzahl = @Anzahl + validation.ranking
     	@Count = @Count + 1
     	end
     	@Durschnitt = @Anzahl/@Count
		"#{@Durschnitt}"


	end
end

Klausuren/ontrack/app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :start_date %><br>
    <%= f.date_select :start_date %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Klausuren/ontrack/app/views/projects/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Projects</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th>Start date</th>
      <th colspan="3"></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.title %></td>
        <td><%= project.description %></td>
        <td><%= project.start_date %></td>
        <td><%= link_to 'Show', project %></td>
        <td><%= link_to 'Edit', edit_project_path(project) %></td>
        <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <td><%if project.validations.empty? %>
            <%=link_to 'Validations', new_project_validation_path(project.id) %>
            <%else %>
            <%=link_to 'Validations', project_validations_path(project.id)   %>
            <%end%>
      </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Project', new_project_path %>

Klausuren/ontrack/app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @project.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @project.description %>
</p>

<p>
  <strong>Start date:</strong>
  <%= @project.start_date %>
</p>

<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %> |
<%= link_to 'Validations', project_validations_path(@project.id) %>