Rails/Projekte/ontrack/config/routes.rb
Rails.application.routes.draw do
  
  root 'projects#index'

  resources :projects do
   resources :tasks
  end
  

  

end

Rails/Projekte/ontrack/app/models/project.rb
class Project < ActiveRecord::Base
	has_many :tasks
	
	validates :title, length: { minimum: 5 }	#Zeichenläge min. 5 Zeichen
	validate :start_date_cannot_be_in_the_past #Abfrage ob das Start_date in der Zukunft liegt

	def start_date_cannot_be_in_the_past #Hier wird die Methode/Bedingung für die Validation festgelegt
  	errors.add(:start_date, "Projektstart muss in der Zukunft liegen") if !start_date.blank? && start_date < Date.today
	end
end

Rails/Projekte/ontrack/app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :project
end

Rails/Projekte/ontrack/app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
before_action :set_project, only: [:edit, :destroy, :update, :show]

	def index
		@projects = Project.all 
	end

	def show
	end

	def edit
	end

	def new
		@project = Project.new
	end

	def update
		if @project.update(project_params)
			redirect_to projects_url, notice:"Update war erfolgreich."
		else
			render :edit
		end
	end

	def destroy
		@project.destroy
		redirect_to projects_url, notice: "Projekt #{@project.title} wurde gelöscht"
	end

	def create
		@project = Project.new(project_params)	
		if @project.save
			redirect_to projects_url, notice: "Erfolgreich gespeichert"
		else 
			render "new"
		end
	end

	private
		def project_params 
			params.require(:project).permit(:title, :description, :start_date)
		end

		def set_project
			@project = Project.find(params[:id])
		end
		
end

Rails/Projekte/ontrack/app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  before_action :set_project
  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = @project.tasks
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = @project.tasks.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = @project.tasks.new(task_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to project_task_path(@project.id, @task.id)}#@task, notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to project_task_path(@project.id, @task.id), notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.delete
    respond_to do |format|
      format.html { redirect_to project_tasks_path(@project), notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    def set_project
      @project = Project.find(params[:project_id])
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:title, :description, :start_date, :end_date, :project_id)
    end
end

Rails/Projekte/ontrack/app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
<%= render "shared/errors", object: @project %>

	<div class="row">
		<div class="medium-3 columns">
			<%= f.label :title%>
		</div>
		<div class="medium-9 columns">
			<%= f.text_field :title %>
		</div>
	</div>

	<div class="row">
		<div class="medium-3 columns">
			<%= f.label :description %>
		</div>
		<div class="medium-9 columns">
			<%= f.text_area :description %>
		</div>
	</div>

	<div class="row">
		<div class="medium-3 columns">
			<%= f.label :start_date %>
		</div>
		<div class="medium-9 columns">
			<%= f.date_select :start_date %> 
		</div>
	</div>
	<div class="row">
		<div class="medium-3 columns">&nbsp;</div>
			<div class="medium-9 columns">
				<%= f.submit "Abschicken", class: "button" %>
				&nbsp;
				<%= link_to "Zurück", projects_path, class: "button" %>
			</div>
	</div>
	
<% end %>

Rails/Projekte/ontrack/app/views/projects/edit.html.erb
<h3>Projekt editieren</h3>
<%= render "form" %>

Rails/Projekte/ontrack/app/views/projects/index.html.erb
<H3> Listing Projects </h3>

<table>
	<head>
		<tr>
			<td>Title</td>
			<td>Description</td>
			<td>Start Date</td>
		</tr>
	</head>
	<body>
		<% @projects.each do |project| %>
		<tr>
			<td><%= project.title %> </td>
			<td><%= project.description %> </td>
			<td><%= project.start_date %> </td>
			<td><%= link_to "<i class='fi-eye'></i>".html_safe, project_path(project.id)%></td>
			<td><%= link_to "<i class='fi-pencil'></i>".html_safe, edit_project_path(project.id)%></td>
			<td><%= link_to "<i class='fi-trash'></i>".html_safe, project_path(project.id), method: :delete, data: {confirm: "Wirklich löschen?"}%></td>
		</tr>
		<% end %>
	</body>
</table>
<%= link_to "Neues Projekt anlegen", new_project_path, class: "button" %>

Rails/Projekte/ontrack/app/views/projects/new.html.erb
<h3>Neues Projekt </h3>
<%= render "form" %>

Rails/Projekte/ontrack/app/views/projects/show.html.erb
<h3>Projekt: <%= @project.title %></h3>

<div class="panel">
	Startet am: <%= @project.start_date %>
	<hr>
	<%= @project.description %>
</div>

<%= link_to "Projekt Tasks anzeigen", project_tasks_path(@project) %>